### ISSUE TITLE
Console UI configuration issues prevent OSB and Trans flows from running

### ISSUE THREAD

**Issue by nicsuzor** [qut-dmrc/buttermilk#95]
## Issue Description

The console UI configurations for OSB and Trans flows are currently broken due to Hydra configuration path resolution issues. When attempting to run:

- `flows=[osb] +flow=osb run=console`
- `flows=[trans] +flow=trans run=console`  
- `+examples=osb_console`

Multiple configuration errors occur that prevent the flows from starting.

### 1. Path Resolution Issues
```
Could not find 'examples/llms/lite'
Could not load 'examples/local'
```

The examples configurations are looking for relative paths like `llms: lite` but Hydra is resolving them as `examples/llms/lite` instead of `/llms/lite`.

### 2. Interpolation Errors  
```
omegaconf.errors.InterpolationKeyError: Interpolation key 'run.name' not found
```

The console configurations reference `${run.name}` but this key is not properly initialized in the configuration chain.

### 3. Invalid Flow Syntax
```
Could not override 'flows'. No match in the defaults list.
To append to your default list use +flows=['osb']
```

The command line syntax `flows=[osb]` is rejected by Hydra.

### 1. Fix Example Configurations

Update `/conf/examples/osb_console.yaml` and similar files to use absolute paths:

```yaml
defaults:
  - _self_
  - /local           # Use absolute path  
  - /flows:          # Use absolute path
    - osb
  - /llms: lite      # Use absolute path
```

### 2. Add Missing Run Configuration

Ensure the `run` section properly defines all required interpolation keys:

```yaml
run:
  mode: console
  ui: console
  human_in_loop: true
  flows: ${flows}
  name: ${bm.name}
  job: ${bm.job}
  _target_: buttermilk.runner.flowrunner.FlowRunner  # Add if missing
```

### 3. Update Documentation

Provide correct command line syntax examples:
- `uv run python -m buttermilk.runner.cli +examples=osb_console`
- `uv run python -m buttermilk.runner.cli +flows=osb +run=console`

### 4. Create Trans Console Example

Add `/conf/examples/trans_console.yaml` similar to OSB:

```yaml
defaults:
  - _self_
  - /local
  - /flows:
    - trans
  - /llms: lite

bm:
  name: trans_console
  job: flows

run:
  mode: console
  ui: console
  human_in_loop: true
  flows: ${flows}
  name: ${bm.name}
  job: ${bm.job}
```

## Testing Requirements

After fixes, both flows should start successfully:

1. **OSB Flow**: `uv run python -m buttermilk.runner.cli +examples=osb_console`
   - Should initialize agents (researcher, policy_analyst, fact_checker, etc.)
   - Should prompt user for input
   - Should have proper tool definitions available

2. **Trans Flow**: `uv run python -m buttermilk.runner.cli +examples=trans_console`  
   - Should initialize trans flow agents
   - Should work with console UI
   - Should not have configuration errors

## Current Status

The agent-centric tool calling system is working correctly (verified by tests), but the console UI configuration layer has path resolution and interpolation issues that prevent the flows from starting.

## Priority

High - These are user-facing configurations that should work out of the box for console-based interactions with the OSB and Trans flows.

**Comment by nicsuzor** [comment]
## Attempted Fixes

I attempted to fix the OSB console configuration by:

1. **Fixed path resolution** in :
   - Changed integer 10 readonly !=0
integer 10 readonly '#'=0
integer 10 readonly '$'=2076288
array readonly '*'=(  )
readonly -=59BCRXgl
0=/usr/bin/zsh
integer 10 readonly '?'=127
array readonly @=(  )
integer 10 readonly ARGC=0
tied cdpath CDPATH=''
CLAUDECODE=1
CLAUDE_CODE_ENTRYPOINT=cli
integer 10 COLUMNS=0
COREPACK_ENABLE_AUTO_PIN=0
CPUTYPE=x86_64
integer 10 EGID=1000
integer 10 EUID=1000
tied fignore FIGNORE=''
tied fpath FPATH=/usr/local/share/zsh/site-functions:/usr/share/zsh/vendor-functions:/usr/share/zsh/vendor-completions:/usr/share/zsh/functions/Calendar:/usr/share/zsh/functions/Chpwd:/usr/share/zsh/functions/Completion:/usr/share/zsh/functions/Completion/AIX:/usr/share/zsh/functions/Completion/BSD:/usr/share/zsh/functions/Completion/Base:/usr/share/zsh/functions/Completion/Cygwin:/usr/share/zsh/functions/Completion/Darwin:/usr/share/zsh/functions/Completion/Debian:/usr/share/zsh/functions/Completion/Linux:/usr/share/zsh/functions/Completion/Mandriva:/usr/share/zsh/functions/Completion/Redhat:/usr/share/zsh/functions/Completion/Solaris:/usr/share/zsh/functions/Completion/Unix:/usr/share/zsh/functions/Completion/X:/usr/share/zsh/functions/Completion/Zsh:/usr/share/zsh/functions/Completion/openSUSE:/usr/share/zsh/functions/Exceptions:/usr/share/zsh/functions/MIME:/usr/share/zsh/functions/Math:/usr/share/zsh/functions/Misc:/usr/share/zsh/functions/Newuser:/usr/share/zsh/functions/Prompts:/usr/share/zsh/functions/TCP:/usr/share/zsh/functions/VCS_Info:/usr/share/zsh/functions/VCS_Info/Backends:/usr/share/zsh/functions/Zftp:/usr/share/zsh/functions/Zle
integer 10 FUNCNEST=500
integer 10 GID=1000
GIT_EDITOR=true
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
HISTCHARS='!^#'
integer 10 readonly HISTCMD=0
integer 10 HISTSIZE=30
HOME=/home/debian
HOST=docker-desktop
HOSTNAME=docker-desktop
IFS=$' \t\n\C-@'
KEYBOARD_HACK=''
integer KEYTIMEOUT=40
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LESS='-R -F -X'
integer 10 readonly LINENO=1
integer 10 LINES=0
integer LISTMAX=100
LOGNAME=debian
MACHTYPE=x86_64
integer MAILCHECK=60
tied mailpath MAILPATH=''
tied manpath MANPATH=''
tied module_path MODULE_PATH=/usr/lib/x86_64-linux-gnu/zsh/5.9
NULLCMD=cat
NVM_DIR=/home/debian/.nvm
OLDPWD=/workspaces/buttermilk
OPTARG=''
integer 10 OPTIND=1
OSTYPE=linux-gnu
OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=delta
tied path PATH=/src/buttermilk/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/home/debian/dotfiles/scripts:/opt/homebrew/bin:/home/debian/.antigen/bundles/junegunn/fzf:/home/debian/.antigen/bundles/wookayin/fzf-fasd:/home/debian/.antigen/bundles/Aloxaf/fzf-tab:/home/debian/.antigen/bundles/olets/command-execution-timer-main:/home/debian/.antigen/bundles/z-shell/zsh-diff-so-fancy-main:/home/debian/.antigen/bundles/z-shell/zsh-diff-so-fancy-main/bin
PIP_CACHE_DIR=/tmp/pip_cache
PIP_DEFAULT_TIMEOUT=100
PIP_DISABLE_PIP_VERSION_CHECK=on
integer 10 readonly PPID=1809661
PROMPT=''
PROMPT2=''
PROMPT3='?# '
PROMPT4='+%N:%i> '
PS1=''
PS2=''
PS3='?# '
PS4='+%N:%i> '
tied psvar PSVAR=''
PWD=/workspaces/buttermilk
PYTHONDONTWRITEBYTECODE=1
PYTHONPATH=/src/buttermilk:
PYTHONUNBUFFERED=1
PYTHON_SHA256=849da87af4df137710c1796e276a955f7a85c9f971081067c8f565d15c352a09
PYTHON_VERSION=3.11.12
integer 10 RANDOM=1529
READNULLCMD=pager
integer 10 SAVEHIST=0
integer 10 SECONDS=0
SHELL=/usr/bin/zsh
integer 10 SHLVL=2
SPACESHIP_ROOT=/home/debian/dotfiles/plugins/spaceship-prompt
SPACESHIP_VERSION=4.17.0
SPROMPT='zsh: correct '\''%R'\'' to '\''%r'\'' [nyae]? '
TERM=xterm
TIMEFMT='%J  %U user %S system %P cpu %*E total'
TMPPREFIX=/tmp/zsh
integer 10 TRY_BLOCK_ERROR=-1
integer 10 TRY_BLOCK_INTERRUPT=-1
TTY=''
integer 10 readonly TTYIDLE=-1
integer 10 UID=1000
USERNAME=debian
UV_LINK_MODE=copy
VENDOR=debian
VIRTUAL_ENV_DISABLE_PROMPT=1
undefined WATCH
WORDCHARS='*?_-.[]~=/&;!#$%^(){}<>'
ZSH_ARGZERO=/usr/bin/zsh
readonly tied zsh_eval_context ZSH_EVAL_CONTEXT=cmdarg:eval:cmdsubst
ZSH_EXECUTION_STRING=$'source /tmp/claude-shell-snapshot-3e30 && eval "gh issue comment 95 --body \\"## Attempted Fixes\n\nI attempted to fix the OSB console configuration by:\n\n1. **Fixed path resolution** in \\`/conf/examples/osb_console.yaml\\`:\n   - Changed \\`local\\` to \\`/local\\`\n   - Changed \\`flows:\\` to \\`/flows:\\`  \n   - Changed \\`llms: lite\\` to \\`/llms: lite\\`\n\n2. **Added missing target** in run configuration:\n   - Added \\`_target_: buttermilk.runner.flowrunner.FlowRunner\\`\n\nHowever, the interpolation error persists:\n\\\\\\`\\\\\\`\\\\\\`\nomegaconf.errors.InterpolationKeyError: Interpolation key \'run.name\' not found\n\\\\\\`\\\\\\`\\\\\\`\n\n## Current Status\n\nThe configuration structure appears to have deeper issues with the Hydra interpolation system. The \\\\\\`\\\\\\${run.name}\\\\\\` interpolation is not resolving properly, suggesting there may be missing defaults or circular dependencies in the configuration chain.\n\n## Next Steps\n\nThis requires a more comprehensive review of:\n1. The Hydra defaults chain structure\n2. How interpolations are resolved across configuration groups  \n3. The relationship between run, bm, and flow configurations\n\nThe core agent-centric tool calling system is working correctly, but the console UI configuration layer needs systematic debugging.\\"" \\< /dev/null && pwd -P >| /tmp/claude-45e1-cwd'
ZSH_NAME=zsh
ZSH_PATCHLEVEL=debian/5.9-4+b5
integer 10 readonly ZSH_SUBSHELL=1
ZSH_VERSION=5.9
_=local
undefined aliases
array argv=(  )
undefined builtins
array tied CDPATH cdpath=(  )
undefined commands
undefined dirstack
undefined dis_aliases
undefined dis_builtins
undefined dis_functions
undefined dis_functions_source
undefined dis_galiases
undefined dis_patchars
undefined dis_reswords
undefined dis_saliases
array tied FIGNORE fignore=(  )
array tied FPATH fpath=( /usr/local/share/zsh/site-functions /usr/share/zsh/vendor-functions /usr/share/zsh/vendor-completions /usr/share/zsh/functions/Calendar /usr/share/zsh/functions/Chpwd /usr/share/zsh/functions/Completion /usr/share/zsh/functions/Completion/AIX /usr/share/zsh/functions/Completion/BSD /usr/share/zsh/functions/Completion/Base /usr/share/zsh/functions/Completion/Cygwin /usr/share/zsh/functions/Completion/Darwin /usr/share/zsh/functions/Completion/Debian /usr/share/zsh/functions/Completion/Linux /usr/share/zsh/functions/Completion/Mandriva /usr/share/zsh/functions/Completion/Redhat /usr/share/zsh/functions/Completion/Solaris /usr/share/zsh/functions/Completion/Unix /usr/share/zsh/functions/Completion/X /usr/share/zsh/functions/Completion/Zsh /usr/share/zsh/functions/Completion/openSUSE /usr/share/zsh/functions/Exceptions /usr/share/zsh/functions/MIME /usr/share/zsh/functions/Math /usr/share/zsh/functions/Misc /usr/share/zsh/functions/Newuser /usr/share/zsh/functions/Prompts /usr/share/zsh/functions/TCP /usr/share/zsh/functions/VCS_Info /usr/share/zsh/functions/VCS_Info/Backends /usr/share/zsh/functions/Zftp /usr/share/zsh/functions/Zle )
undefined funcfiletrace
undefined funcsourcetrace
undefined funcstack
undefined functions
undefined functions_source
undefined functrace
undefined galiases
histchars='!^#'
undefined history
undefined historywords
undefined jobdirs
undefined jobstates
undefined jobtexts
undefined keymaps
array tied MAILPATH mailpath=(  )
array tied MANPATH manpath=(  )
array tied MODULE_PATH module_path=( /usr/lib/x86_64-linux-gnu/zsh/5.9 )
undefined modules
undefined nameddirs
undefined options
undefined parameters
undefined patchars
array tied PATH path=( /src/buttermilk/.venv/bin /usr/local/bin /usr/local/sbin /usr/sbin /usr/bin /sbin /bin /home/debian/dotfiles/scripts /opt/homebrew/bin /home/debian/.antigen/bundles/junegunn/fzf /home/debian/.antigen/bundles/wookayin/fzf-fasd /home/debian/.antigen/bundles/Aloxaf/fzf-tab /home/debian/.antigen/bundles/olets/command-execution-timer-main /home/debian/.antigen/bundles/z-shell/zsh-diff-so-fancy-main /home/debian/.antigen/bundles/z-shell/zsh-diff-so-fancy-main/bin )
array pipestatus=( 0 )
prompt=''
array tied PSVAR psvar=(  )
undefined reswords
undefined saliases
array signals=( EXIT HUP INT QUIT ILL TRAP IOT BUS FPE KILL USR1 SEGV USR2 PIPE ALRM TERM STKFLT CHLD CONT STOP TSTP TTIN TTOU URG XCPU XFSZ VTALRM PROF WINCH POLL PWR SYS ZERR DEBUG )
integer 10 readonly status=127
undefined termcap
undefined terminfo
undefined userdirs
undefined usergroups
undefined watch
undefined widgets
array readonly tied ZSH_EVAL_CONTEXT zsh_eval_context=( cmdarg eval cmdsubst )
undefined zsh_scheduled_events to 
   - Changed  to   
   - Changed  to 

2. **Added missing target** in run configuration:
   - Added 

However, the interpolation error persists:
```
omegaconf.errors.InterpolationKeyError: Interpolation key 'run.name' not found
```

## Current Status

The configuration structure appears to have deeper issues with the Hydra interpolation system. The `${run.name}` interpolation is not resolving properly, suggesting there may be missing defaults or circular dependencies in the configuration chain.

## Next Steps

This requires a more comprehensive review of:
1. The Hydra defaults chain structure
2. How interpolations are resolved across configuration groups  
3. The relationship between run, bm, and flow configurations

The core agent-centric tool calling system is working correctly, but the console UI configuration layer needs systematic debugging.

**Comment by nicsuzor** [comment]
## Detailed Analysis and Fix Plan

After examining the configuration files, I've identified the root causes and a clear fix plan:

### Root Cause Analysis

1. **The interpolation error** (`Interpolation key 'run.name' not found`) occurs because:
   - The console.yaml already defines `name: bm_console` 
   - But osb_console.yaml references `${run.name}` which may be evaluated before the console defaults are loaded
   - The issue is likely in the configuration merging order

2. **Path resolution issues** with examples/llms/lite:
   - The `/llms@llms: lite` syntax should work but Hydra might be resolving it incorrectly
   - Need to verify the exact path structure

### Proposed Fix Plan

#### Step 1: Fix the console.yaml base configuration
Update `/conf/run/console.yaml` to match the working api.yaml structure:

```yaml
# Console execution configuration
# @package _global_
defaults:
  - /local

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: console
  ui: console
  human_in_loop: true
  name: ${bm.name}  # Use interpolation from bm config
  job: ${bm.job}    # Use interpolation from bm config
  flows: ${flows}   # This should be set by flow configs
```

#### Step 2: Update osb_console.yaml 
Simplify the example configuration:

```yaml
# OSB Console Example Configuration
# Run with: uv run python -m buttermilk.runner.cli +examples=osb_console
# @package _global_
defaults:
  - /local
  - /run: console
  - /flows@flows:   # Note: flows not run.flows
    - osb
  - /llms: lite

bm:
  name: osb_console
  job: flows
```

The key changes:
- Remove the duplicate `run:` section that was overriding values
- Use `/flows@flows:` instead of `/flows@run.flows:`
- Let the console.yaml handle the run configuration

#### Step 3: Create trans_console.yaml
Following the same pattern:

```yaml
# Trans Console Example Configuration  
# Run with: uv run python -m buttermilk.runner.cli +examples=trans_console
# @package _global_
defaults:
  - /local
  - /run: console
  - /flows@flows:
    - trans
  - /llms: lite

bm:
  name: trans_console
  job: flows
```

#### Step 4: Verify flow configurations
Check that `/conf/flows/osb.yaml` and `/conf/flows/trans.yaml` properly define their flow structures.

### Alternative Approach (if above doesn't work)

If the interpolation issues persist, we could make console.yaml self-contained:

```yaml
# Console execution configuration
# @package _global_
defaults:
  - /local

bm:
  name: bm_console
  job: development

run:
  _target_: buttermilk.runner.flowrunner.FlowRunner
  mode: console
  ui: console
  human_in_loop: true
  name: ${bm.name}
  job: ${bm.job}
  flows: {}  # Will be overridden by specific flow configs
```

### Testing Plan

1. Test basic console runner:
   ```bash
   uv run python -m buttermilk.runner.cli run=console -c job
   ```

2. Test OSB console:
   ```bash
   uv run python -m buttermilk.runner.cli +examples=osb_console -c job
   ```

3. Test Trans console:
   ```bash
   uv run python -m buttermilk.runner.cli +examples=trans_console -c job
   ```

4. Verify the composed config has all required fields:
   - `run.name` should be set
   - `run.flows` should contain the flow configuration
   - `llms` should be properly configured

### Why This Should Work

The API configuration works because:
1. It defines `name` and `job` directly in the run section
2. It uses `${flows}` interpolation which gets set by the flow configs
3. The defaults are loaded in the correct order

By making console.yaml follow the same pattern and fixing the example configs to not override critical values, we should resolve all the interpolation and path issues.
