### ISSUE TITLE
Refactored RAG architecture: Clean separation of search tool and agent

### ISSUE THREAD

**Issue by nicsuzor** [qut-dmrc/buttermilk#99]
## Summary

Completed a major refactoring to cleanly separate ChromaDB search functionality (tool) from the agent that uses it (LLMAgent with template). This addresses the architectural issues identified in #98.

### Created Standalone Search Tool
- `buttermilk.tools.chromadb_search.ChromaDBSearchTool`
  - Configurable with any ChromaDB instance
  - Provides `search()` method returning `SearchResult` objects
  - Exposes as `FunctionTool` for agent integration
  - No agent logic - just pure search functionality

### Created Simple Research Agent
- `conf/agents/research_agent.yaml` - Standard LLMAgent configuration
- `templates/prompt/research_synthesis.jinja2` - Template with search/synthesis logic
- Agent handles:
  - Understanding user queries
  - Calling search tool (potentially multiple times)
  - Refining searches based on results
  - Synthesizing findings into coherent responses

### Deleted Complex Implementations
- Removed RagAgent, EnhancedRagAgent, RagZot classes
- Deleted 7 outdated YAML configs
- Eliminated mixed tool/agent logic

### Updated Flows
- `osb.yaml` - Now uses clean tool + agent approach
- `clean_rag.yaml` - Example of the new architecture

## Architecture Benefits

1. **Separation of Concerns**
   - Tools do one thing: provide functionality
   - Agents do one thing: orchestrate and synthesize
   - Templates contain the workflow logic

2. **Modularity**
   - Any agent can use the search tool
   - Search tool works with any ChromaDB instance
   - Easy to swap different search strategies

3. **Simplicity**
   - No complex inheritance hierarchies
   - No tool registration complexity
   - Clear data flow: User → Host → Agent → Tool → Agent → User

## Example Configuration

```yaml
# Tool configuration
osb_search:
  _target_: buttermilk.tools.chromadb_search.ChromaDBSearchTool
  collection_name: ${storage.osb_vector.collection_name}
  persist_directory: ${storage.osb_vector.persist_directory}
  n_results: 10

# Agent configuration  
research_agent:
  role: "RESEARCHER"
  agent_obj: LLMAgent  # Just a standard LLM agent
  tools: ${...parameters.search_tool}
  parameters:
    template: research_synthesis
```

## Usage Pattern

1. User asks: "What are the data retention policies?"
2. Host routes to RESEARCHER
3. RESEARCHER (via template logic):
   - Calls search_vector_database("data retention policies")
   - Analyzes results
   - Maybe refines: search_vector_database("data storage duration requirements")
   - Synthesizes findings
4. Returns coherent answer to user

## Breaking Changes

This is a breaking change for any flows using the old RAG agents. Migration:
- Replace agent references to use `research_agent`
- Add tool configuration for ChromaDB search
- Update flow parameters as shown in `clean_rag.yaml`

Fixes #98
